### ISSUE TITLE
YouTube has changed the unit of ¥(yen) with JP¥ and now these old units won't work

### ISSUE THREAD

**Issue by DSRLIN** [eai04191/SuperChatCalc#1]

**Comment by DSRLIN** [comment]
just change the 
const baseUnit = ["¥", "￥"];
to
const baseUnit = ["JP¥", "JP￥"];
could solve this problem

**Comment by eai04191** [comment]
Hi, thank you for making Issue.
As you may have noticed, the project is abandoned because I no longer watch YouTube Live.
I think many problems need to be fixed, but probably not.
Anyway, this project is MIT licensed, so you are free to modify and fork if you want to use it.
